Challenge
DeVuDeveloper/test-app pull request #1
Opened 2023-07-31 14:54 UTC by DeVuDeveloper

**Refactoring and Setup:**

- Added essential gems for enhanced functionality: `simple_form`, `turbo-rails`, `stimulus-rails`, `redis`, and `sidekiq`.
- Significantly improved page rendering by leveraging turbo frames and turbo streams.
- Implemented form validation to provide a smoother user experience.
- Conducted comprehensive tests prior to actual code implementation.
- Refactored the codebase and introduced view components for better maintainability and readability.
- Added tests before starting the problem-solving process, ensuring that new features and changes are thoroughly validated.

2023-08-08 10:14 UTC, joelmoss commented on app/src/orders/components/OrderRow.jsx
> +      <td data-testid="order-id">{id}</td>
test data/attributes should not be in non-test code.

2023-08-08 14:16 UTC, DeVuDeveloper commented
Hi Joe,

Thank you for your prompt response and for reviewing the code. I had some
errors in the tests, which I added for debugging purposes. I've made
changes to both the component and the test, and I now have an update for
the pull request. I have some free time now, and I want to see how the Gem
Proscenium will collaborate with Tailwind CSS and Vite. After that, I'll
work on styling to make it resemble the Digital Oven design more closely.

Could you please take a look at the update? I'll also send you the update:
<https://github.com/DeVuDeveloper/test-app/pull/1>







*Replaced the script-based test execution in package.json with a Jest
configuration file and a setup file in the root directory for more
organized test management.Introduced a testing helper for testing Stimulus
controllers, streamlining the testing process and ensuring consistent
controller behavior.Added a new test for the CookiesController in Stimulus
to verify its functionality and behavior.Restored the Pagination component
to the codebase and conducted debugging to ensure proper integration with
fulfillment actions when used in conjunction with paginations.Eliminated
the usage of data-test-id attributes from the OrderRaw component, improving
test readability and simplifying maintenance. The corresponding test for
this component was also updated accordingly.Addressed React update warnings
by wrapping asynchronous operations with the act function, ensuring that
state updates are handled correctly during testing.Integrated Jest tests
into GitHub Actions.*

*Once again, thank you for your time.*

Best regards,
Dejan

On Tue, Aug 8, 2023 at 12:14 PM Joel Moss ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In app/src/orders/components/OrderRow.jsx
> <https://github.com/DeVuDeveloper/test-app/pull/1#discussion_r1286911138>:
>
> > +    setIsFulfilling(true);
> +
> +    try {
> +      await onFulfillOrder(order);
> +      setIsFulfilling(false);
> +      setCurrentFulfilledStatus(true);
> +      storeFulfilledStatus(id, true);
> +    } catch (error) {
> +      console.error('Error fulfilling order:', error);
> +      setIsFulfilling(false);
> +    }
> +  };
> +
> +  return (
> +    <tr>
> +      <td data-testid="order-id">{id}</td>
>
> test data/attributes should not be in non-test code.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DeVuDeveloper/test-app/pull/1#pullrequestreview-1566971450>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWLERYJ3BTJLCQCEKWDLD73XUIGR5ANCNFSM6AAAAAA26MHOOM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-08-15 15:39 UTC, muhammad-ur-rehman requested changes

2023-08-15 15:39 UTC, muhammad-ur-rehman commented on .eslintrc
> +}
add empty line at the EOF

2023-08-15 15:39 UTC, muhammad-ur-rehman commented on .github/workflows/linters.yml
> +        run: npm test -- --ci --coverage
empty line EOF.
Please look at all of the files

2023-08-15 15:39 UTC, muhammad-ur-rehman commented on .vscode/settings.json
> +}
why we need this file?

2023-08-15 15:39 UTC, muhammad-ur-rehman commented on README.md
> +  <img src="app/assets/images/bakery3.png" alt="bakery 3" width="30%">
dont need to increase code size for the README file images are not required in readme until they are very important if it is important use any other free/paid source to place pictures there

2023-08-15 15:39 UTC, muhammad-ur-rehman commented on __tests__/stimulus/cookies_controler.test.js
> +
empty spaces

2023-08-15 15:39 UTC, muhammad-ur-rehman commented on app/components/ovens/cookie_info_component.html.erb
> +          <%= pluralize(@oven.cookies.size, "cookie") %> with <%= @oven.first_cookie_fillings || "no fillings" %>
have you handled `@oven.cookies` (n+1) in the code base?

2023-08-15 15:39 UTC, muhammad-ur-rehman commented on app/controllers/application_controller.rb
> +    end
make these private i think we dont need them available in all controllers

2023-08-15 15:39 UTC, muhammad-ur-rehman commented on app/controllers/cookies_controller.rb
> +            format.turbo_stream { flash.now[:alert] = flash.now[:alert] }
complexity of this method is very high reduce it

2023-08-15 15:39 UTC, muhammad-ur-rehman commented on app/controllers/cookies_controller.rb
> +              format.turbo_stream.append("cookies", partial: "cookies/created_cookie")
too many render lines there should be only 1 render for html, 1 for tubo etc.

2023-08-15 15:39 UTC, muhammad-ur-rehman commented on app/controllers/cookies_controller.rb
> +            format.html { render :new, alert: flash.now[:alert] }
this method is doing magic?
you have to break this into smaller method follow SRP, DRY

2023-08-15 15:39 UTC, muhammad-ur-rehman commented on app/controllers/cookies_controller.rb
> +    total_price = params[:total_price].to_f
always permit params before using

2023-08-15 15:39 UTC, muhammad-ur-rehman commented on app/controllers/cookies_controller.rb
> +  def claim_change
if this method is not linked with any route make it private

2023-08-15 15:39 UTC, muhammad-ur-rehman commented on app/controllers/cookies_controller.rb
> +      current_user.add_to_balance(change_to_claim)
what if this fails it will still return success

2023-08-15 15:39 UTC, muhammad-ur-rehman commented on app/controllers/cookies_controller.rb
> +  end
you need to slim the controller make use of concern or hellper or service what ever make sense

2023-08-15 15:39 UTC, muhammad-ur-rehman commented on app/controllers/ovens_controller.rb
>    end
code reusability + silm all the controllers

2023-08-15 15:39 UTC, muhammad-ur-rehman commented on app/controllers/users_controller.rb
> +  before_action :authenticate_user!, only: [:show, :update, :add_balance]
this controller only have 1 method and you are authenticating for 3 methods

2023-08-15 15:39 UTC, muhammad-ur-rehman commented on app/javascript/controllers/application.js
> +export { application }
extra line EOF

2023-08-15 15:39 UTC, muhammad-ur-rehman commented on app/javascript/controllers/cookies_controller.js
> +
setup linter for these also

2023-08-15 15:39 UTC, muhammad-ur-rehman commented on app/javascript/entrypoints/application.js
> +// import '~/index.css'
remove unnecessary comments

2023-08-15 15:39 UTC, muhammad-ur-rehman commented on app/javascript/entrypoints/application.js
> +
you are printing this on console for production as well?

2023-08-15 15:39 UTC, muhammad-ur-rehman commented on app/services/cookies/create_service.rb
> +    @params = params
how you know what variables you need in params

2023-08-15 15:39 UTC, muhammad-ur-rehman commented on app/services/cookies/create_service.rb
> +      cookie.update(cooked_at: Time.now + cooking_time)
what if this breaks?

2023-08-15 15:39 UTC, muhammad-ur-rehman commented on app/src/orders/App.jsx
> +
linting issues

2023-08-15 15:39 UTC, muhammad-ur-rehman commented on app/src/orders/components/OrderRow.jsx
> +
linting

2023-08-15 15:39 UTC, muhammad-ur-rehman commented on app/src/orders/hooks/UseFetchOrders.jsx
> +
linting

2023-08-15 15:39 UTC, muhammad-ur-rehman commented on app/views/layouts/_navigation_links.html.erb
> +    <%= link_to 'Order listing', orders_path, class: 'nav-link', data: {turbo: false} %>
one question why you need the turbo fase?

2023-08-15 15:39 UTC, muhammad-ur-rehman commented on app/views/layouts/application.css
> +  color: hsl(120, 96%, 53%);
make use of variables in scss

2023-08-15 15:39 UTC, muhammad-ur-rehman commented on app/views/ovens/_toggle.html.erb
> +
linting issues in all of the HTML files

2023-08-19 12:54 UTC, DeVuDeveloper commented on app/views/layouts/_navigation_links.html.erb
> +    <%= link_to 'Order listing', orders_path, class: 'nav-link', data: {turbo: false} %>
It is React, so I don't need turbo.

2023-08-23 14:50 UTC, merged